[show]
no_os = false
no_arch = false
no_kernel = false
no_uptime = false
no_up_since = false
no_wm = false
no_de = false
no_gtk2_theme = true
no_gtk2_Icon_theme = true
no_gtk2_font = true
no_gtk2_cursor_theme = true
no_gtk3_theme = true
no_gtk3_icon_theme = true
no_gtk3_font = true
no_gtk3_cursor_theme = true
no_terminal = false
no_shell = false
no_editor = false
no_packages = false
no_memory = false
no_swap = true
no_cpu = false
no_root = false
no_home = false

[options]
sep = " ->"
memory_unit = "mb"
swap_unit = "mb"
disk_unit = "gb"
paths = ["/usr", "/tmp"]
path_full = false
shell_full = true
up_since_format = "%A, %d %B %Y at %r %Z"
no_color = false

[colors]
name_color = "150"
text_color = "white+h"
sep_color = "191"
body_color = "cyan+h:cyan"
