[show]
noOS = false
noArch = false
noKernel = false
noUptime = false
noUpSince = false
noWM = false
noDE = false
noGTK2Theme = true
noGTK2IconTheme = true
noGTK2Font = true
noGTK2CursorTheme = true
noGTK3Theme = true
noGTK3IconTheme = true
noGTK3Font = true
noGTK3CursorTheme = true
noTerminal = false
noShell = false
noEditor = false
noPackages = false
noMemory = false
noSwap = true
noCPU = false
noRoot = false
noHome = false

[options]
sep = " ->"
memoryUnit = "mb"
swapUnit = "mb"
diskUnit = "gb"
paths = ["/usr", "/tmp"]
pathFull = false
shellFull = true
upSinceFormat = "%A, %d %B %Y at %r %Z"
noColor = false

[colors]
nameColor = "150"
textColor = "white+h"
sepColor = "191"
bodyColor = ["cyan+h", "cyan"]
