[show]
noOS = false
noArch = false
noKernel = false
noUptime = false
noUpSince = false
noWM = false
noDE = false
noTerminal = false
noShell = false
noEditor = false
noPackages = false
noMemory = false
noSwap = true
noCPU = false
noRoot = false
noHome = false

[options]
sep = " ->"
memoryUnit = "mb"
swapUnit = "mb"
diskUnit = "gb"
paths = ["/usr", "/tmp"]
pathFull = false
shellFull = true
noColor = false

[colors]
nameColor = "150"
textColor = "white+h"
sepColor = "191"
bodyColor = "69"
